### ISSUE TITLE
Accelerators don't match across rule barriers

### ISSUE THREAD

**Issue by kernow** [kschiess/parslet#102]
As per discussion on irc

These parser rules

``` ruby
rule(:quotes) { str('"') }
rule(:value)  { quotes >> (quotes.absent? >> any).repeat.as(:value) >> quotes }
```

Should be matched by

``` ruby
A = Parslet::Accelerator
A.rule((A.str(:x).absent? >> A.any).repeat) { GobbleUp.new(x) }
```

But currently is not.

**Comment by kschiess** [comment]
Just writing to let you know of my progress here: 

* The whole thing is not trivial, since parsers can be recursive; accelerator application should not be. 
* Have to define what happens on rule barriers; and also: If rule barriers should be part of the matching process at all. 

not trivial ;)

**Comment by kschiess** [comment]
I've got no solution to this. I'll close this ticket for now.
