### ISSUE TITLE
Parser array output

### ISSUE THREAD

**Issue by michaelmior** [kschiess/parslet#114]
It would be nice if it were possible to tell parslet that I always want something to be an array, even if there's only one element. The two rules below are extracted from the getting started example.

```
rule(:arglist)    { expression >> (comma >> expression).repeat }
rule(:funcall)    { identifier.as(:funcall) >> lparen >> arglist.as(:arglist) >> rparen }
```

If `arglist` contains multiple expression, then `arglist` parsed in the context of `funcall` will be an array. However, if it only contains one expression, then it will be a hash. This means additional logic to check whether one or many things were parsed.

It would be nice if this could be handled a bit more automatically. One possibility is something like

```
arglist.as_array(:arglist)
```

This would check if parsing `arglist` results in only a single element and then wrap it in an array. It also keeps backwards compatibility. I think I'll probably start working on a patch, but let me know if this is something you would be interested in accepting or if there's a better way to do the same thing.

**Comment by michaelmior** [comment]
@JESii transforms have to match the entire subtree. Your rule only matches the key `:mc` but the parse tree also has the key `:bc`. You would need to have your rule match a parse tree with both of those keys. You could then turn both into an array at the same time.

**Comment by JESii** [comment]
Thanks, but I'm still having problems:
The parse tree looks like this (same as before):
  `{:mc=>{:spid=>"17560"@0}, :bc=>{:spid=>"16699"@7}}`
So I copied that parse tree, transmogrified it into a rule and just tried to get the transform rule to match:
    `rule({:mc=>{:spid=>simple(:argm)}, :bc=>{:spid=>simple(:argb)}}) { 'abc' }`
Unfortunately, that still doesn't match and just passes through un-transformed.

And even more unfortunately, I will now have to have more transform rules, as I can get parse trees where :mc is already an array or :bc is already an array; like this...
  `{:mc=>{:spid=>"12345"@0}, :bc=>[{:pid=>"17560"@8}, {:pid=>"17899"@15}]}`
It's the nature of the input I'm dealing with -- I want to get an array back out for both :mc and :bc, even they have only one element.

**Comment by JESii** [comment]
OK; figured it out... 

I had already identified 'single' entries versus 'multiple' entries with the ":spid" versus ":pid" name. So, all that was required were the two rules:
```
  rule(:pid => simple(:x)) { Integer(x) }
  rule(:spid => simple(:x)) { [ Integer(x) ] }
```
