### ISSUE TITLE
Blankslate removed

### ISSUE THREAD

**Issue by dancinglightning** [kschiess/parslet#131]
Hi,
i am fiddling with opal, which doesn't even do the require blankslate. So i took the bull by the horns and surprisingly managed :-) https://github.com/salama/parslet/commit/81220d74fa77a4ede5267d4d6fa6ded922b0c548

There were a couple of methods i had to add back into the context, but nothing too big.
I have tested the commit with ruby 1.9.3, 2.0 and 2.1.5, all green. 
So the commit even removed the dependency from the gemspec and everywhere else off course.

I can off course send a pull request but thought you might want to discuss first.

**Comment by dancinglightning** [comment]
btw. i found a bug in opal that trips over <<self

if we could squeeze a space in there at the same time that would be great. So << "space" self
I know it is legal syntax, just opal stumbles. Noticed that after, could you do that? 
There are two occurrences, in context and in parser.
That would be nice. T.

**Comment by dancinglightning** [comment]
any comment ?

**Comment by kschiess** [comment]
Can you create a PR for both? I will be happy to look at those changes.

**Comment by kschiess** [comment]
See PR #132 and PR #133.

**Comment by kschiess** [comment]
See #134

**Comment by kschiess** [comment]
We were unable to find an implementation that keeps present functionality intact.
