### ISSUE TITLE
Suggestion: document infix_expression on the tricks page

### ISSUE THREAD

**Issue by maxjacobson** [kschiess/parslet#135]
I was really glad to find this functionality is native to parslet, but didn't find it while reading the parslet website, and ended up implementing something fairly hacky :smile:

**Comment by kschiess** [comment]
This is not a suggestion box, it is for actual issues or pull requests. The infix parser is documented [here](https://github.com/kschiess/parslet/blob/master/example/prec_calc.rb) and referenced by the main documentation. 

Feel free to propose a change to the documentation, you can find it below the website subdirectory in the project's root.
