### ISSUE TITLE
Github not up to date

### ISSUE THREAD

**Issue by CGamesPlay** [kschiess/parslet#149]
There appear to be several new versions of this gem not reflected in Github. Can you push the latest gem source to the repo or provide directions for where we should get it?

**Comment by CGamesPlay** [comment]
Sorry, just so this is more clear, I'm referring to the 'branches/tags' portion of the repo. The tags don't seem to be pushed even though the gemspec says "1.7.1"

**Comment by kschiess** [comment]
Can you check again. Just did a fresh clone and everything seems to be allright.
