### ISSUE TITLE
Concatinated .maybe statements match "" as "" instead of nil

### ISSUE THREAD

**Issue by postmodern** [kschiess/parslet#155]
### Example

```
class Parser < Parslet::Parser
  root :foo
  rule(:foo) { (str('foo=').maybe >> str('bar').maybe).as(:match) }
end
Parser.new.foo.parse("")
```
### Actual Output

```
# => {:match=>""}
```
### Expected Output

```
# => {:match=>nil}
```

**Comment by postmodern** [comment]
Rewriting the expression as below seems to work:

    rule(:foo) {
      (
        (str('foo=') >> str('bar').maybe) |
        (str('foo=').maybe >> str('bar'))
      ).maybe.as(:value)
    }

**Comment by kschiess** [comment]
Should we act on this? What could be done? 

Our merging algo is a bit finnicky - in theory, we would have to complicate things to cover all cases. But in practice, the heuristics work nicely apart from a few edge cases like this one. SOO ... it's a tradeoff...

**Comment by postmodern** [comment]
Can we add a note about this unexpected behavior somewhere? Kind of surprised me when I stumbled across this.
