### ISSUE TITLE
Raise if transform skips subtree

### ISSUE THREAD

**Issue by ravinggenius** [kschiess/parslet#164]
For my application if a subtree doesn't get matched by a transform rule, I have an error. It would be nice if Parslet could optionally raise an exception to alert when no transform rule matches. The exception should include the unmatched keys and ideally the classes and/or contents of the corresponding values.

I'm sure not everyone would want this behavior, so it should be opt-in somehow. This would be extremely useful to me.

**Comment by ravinggenius** [comment]
Comments? Thoughts? I'm happy to tackle this if that helps.

**Comment by kschiess** [comment]
Would have to be opt-in. Have you got an idea on how to implement this?

**Comment by ravinggenius** [comment]
I would change [`transform_elt`](https://github.com/kschiess/parslet/blob/17b821049bc5dcea575b9c8febe0cfb90903ff0d/lib/parslet/transform.rb#L239) to check `raise_on_unmatch` and either return the node or raise an exception. Sample usage below:

```ruby
class MyTransform < Parslet::Transform
  def self.apply(raw_tree)
    new(raise_on_unmatch: true).apply(raw_tree)
  end
end
```
