### ISSUE TITLE
Various warnings due to uninitialized or unused variables

### ISSUE THREAD

**Issue by ravinggenius** [kschiess/parslet#166]
I'm getting an overwhelming number of warnings when running parslet. Some are issued only a few dozen times while others are issued 10 of thousands of times. In total I get over 48K warnings when running the test suite for my parser.

```
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/atoms/base.rb:86:  warning: assigned but unused variable - value
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/atoms/base.rb:140: warning: instance variable @label not initialized

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/atoms/entity.rb:26: warning: instance variable @parslet not initialized

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/atoms/lookahead.rb:28: warning: assigned but unused variable - value

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/cause.rb:62: warning: instance variable @context not initialized

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/error_reporter/deepest.rb:67: warning: assigned but unused variable - rank

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/source/line_cache.rb:43: warning: instance variable @last_line_end not initialized

/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/parslet-1.7.1/lib/parslet/transform.rb:134: warning: instance variable @__transform_rules not initialized
```

**Comment by ravinggenius** [comment]
I can fix these myself if a pull request would be welcome.

**Comment by kschiess** [comment]
If this is still important to you: Can you maybe provide us with a small example PR to look at?

**Comment by mperham** [comment]
Seeing thousands of errors also, looks like there's a PR now to fix this, @kschiess?

**Comment by kschiess** [comment]
haters gonna hate...

Does the PR fix all of the thousands of errors? Or is it the sample we talked about? 

I am fine with the transformation as executed in the PR and will merge as soon as you say the work is complete.

**Comment by mperham** [comment]
The 1000s of errors are all dupes of 2-3 different warnings.  Happy to verify once you have a fix on master.

**Comment by mperham** [comment]
@kschiess Any chance of a gem release with this fix?

**Comment by mperham** [comment]
(and yes, running master works great and no longer shows any warnings!) 🍰 🎆

**Comment by kschiess** [comment]
1.8.0 just went out. If anything is wrong with it, please let me know.
