### ISSUE TITLE
Any absent repeat fails with undefined method for nil class

### ISSUE THREAD

**Issue by joelmeyerhamme** [kschiess/parslet#169]
```ruby
require 'parslet'
include Parslet

any.absent?.repeat(2,2).parse('')
# => NoMethodError: undefined method `+' for nil:NilClass
```
Is this intended?

The problem appears to be that `any.absent?.parse('')` returns `nil`, which can't be concatenated with the second repetition.

I suggest having `any.absent?.parse('')` return empty string.

**Comment by kschiess** [comment]
`any.absent?` ? Like EOS/EOF? What version of parslet are you using? I just tried this on master and cannot reproduce your NoMethodError.

**Comment by joelmeyerhamme** [comment]
Sorry, had some other things to do. It seems to be fixed now, so i am just going to close the issue.  Thanks for looking into it, though.
