### ISSUE TITLE
missing matches

### ISSUE THREAD

**Issue by pinkynrg** [kschiess/parslet#181]
I wrote a small test like this:

```
class TEST < Parslet::Parser
  rule(:first) { second >> third.maybe }
  rule (:second) { str("A") | str("AB") }
  rule (:third) { str('!') }
  root :first
end
```

shouldn't this example parse all the following inputs?

- A
- AB
- A!
- AB!

In my case it parses only:

- A
- A!

On the other hand if I replace in the "second" rule the "AB" string with a "C" string I can parse the following as expected: 
 
- A
- C
- A!
- C!

**Comment by kschiess** [comment]
The '|' operator prefers left side over right. If the left side match is shorter and matches, the right side will never be tested (no backtracking). 

In other words, your rule ':second' should probably be: 

~~~ruby
rule (:second) { str("AB") | str("A") }
~~~

**Comment by pinkynrg** [comment]
Thanks!

**Comment by pinkynrg** [comment]
My example is tricky, also because I've never built a parser before. Is there a way I can capture with a regex a part of the string to be parsed and then check if the __entire selected substring__ passes a certain rule? Is it something that makes sense when building a parser?

**Comment by pinkynrg** [comment]
I solved by adding a rule that checks using match["..."].present | any.absent?
