### ISSUE TITLE
preprocess string before parsing? 

### ISSUE THREAD

**Issue by sethboyles** [kschiess/parslet#182]
I would like to preprocess a string before the parser parses everything.  For instance, I would like to replace all left and right quote characters `“` `”` with normal quotes `"` rather than having to write the extra cases into all of my rules.   Is there an easy way to handle that in Parslet?  

Thanks

**Comment by kschiess** [comment]
What stops you from handling this in Ruby before using parslet?

**Comment by sethboyles** [comment]
Nothing, just wondering if Parslet provided anything for this.

**Comment by kschiess** [comment]
There would be no good place to do this in the parsing pipeline; it would risk making everything slower. If string.tr or a string.replace can work, I would suggest using that.
