### ISSUE TITLE
`abort` call in infix.rb

### ISSUE THREAD

**Issue by olbrich** [kschiess/parslet#186]
https://github.com/kschiess/parslet/blob/7ac42d9bbd92345e3decf891256097debe51720b/lib/parslet/atoms/infix.rb#L59

This seems like a bad idea.  Hitting this line of code will abruptly terminate your process.  Maybe this was supposed to be a `raise`?

**Comment by kschiess** [comment]
... you might be right. We obviously don't have a test for this path. Would you be able to provide such a test? 

(I'd rather not change this line and still not have a test for it...)
