### ISSUE TITLE
json parser example not work when a array inside like   [{ "b": true, "c": false , "d": [1, 2, 3]}]

### ISSUE THREAD

**Issue by bravywang** [kschiess/parslet#210]
try this:
 [{ "b": true, "c": false , "d": [1, 2, 3]}]
will get:
./xsim:74:in `key': wrong number of arguments (given 0, expected 1) (ArgumentError)

**Comment by kschiess** [comment]
The json parser (which one?) would be an example of a parser, not a production version parser. There are plenty alternatives in the Ruby ecosystem. This issue - AFAIK - does not relate to parslet itself - let me know if you think otherwise; also a pointer to which json parser would be welcome.
