### ISSUE TITLE
2.0.0 git tag is missing

### ISSUE THREAD

**Issue by bastelfreak** [kschiess/parslet#217]
Hi!
thanks for the awesome project! I'm trying to package it for Arch Linux. I noticed that [rubygems](https://rubygems.org/gems/parslet) lists a 2.0.0 release, but github only has a 1.8.2 tag. Could you please add the tag for 2.0.0 as well?

**Comment by bastelfreak** [comment]
@kschiess ping :) 
can you please take a look at the missing git tag?

**Comment by kschiess** [comment]
Hi Tim,

Thanks for the ping. I’ve added the tag, so hopefully you’re on your way.

Cheers,
kaspar
