### ISSUE TITLE
Test with Ruby 3.0

### ISSUE THREAD

**Issue by dosuken123** [kschiess/parslet#222]
Looking at the [.travis.yml](https://github.com/kschiess/parslet/blob/master/.travis.yml), it seems we test only with the following Ruby versions:

```
rvm:
  - "2.2.6"
  - "2.3.3"
  - "2.4.0"
```

We should add "3.0.x" to check the compatibility with Ruby 3.0.

**Comment by kschiess** [comment]
This is adressed by the merged PR #214.
